### ISSUE TITLE
Checklist before PR

### ISSUE THREAD

**Issue by Dergash** [Dergash/Under-the-hood-ReactJS#1]
- [x] Translate all chapters
- [ ] Add glossary
- [ ] Proof read with regard to [official Russian translation of React documentation ](https://ru.react.js.org/docs/getting-started.html) to increase the inconsistency of nomenclature 
- [ ] Translate SVG charts
- [ ] Submit PR
